# Generated by Django 4.1 on 2022-08-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='badges',
            field=models.ManyToManyField(to='main_app.badge'),
        ),
    ]
